[package]
name = "teapot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18.0"
vulkano = "0.34.1"
vulkano-shaders = "0.34.0"
winit = "0.28.0"
egui_winit_vulkano="0.27.0"
